# github repository actions 페이지에 나타날 이름
name: CI/CD using github actions

# event trigger
# main 브랜치에 push 됐을때 실행
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CD:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up jdk'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # https://github.com/actions/setup-java

      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ vars.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      # gradle caching - 빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      ## gradle build
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      ## docker build & push to production
      - name: Docker build & push to prod
        if: contains(github.ref, 'main')
        run: |
          docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ vars.DOCKER_PASSWORD }}
          docker build -t ${{ vars.DOCKER_REPO }} .
          docker push ${{ vars.DOCKER_REPO }}

      ## deploy to production
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        id: deploy
        if: contains(github.ref, 'main')
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.HOST_USERNAME }}
          key: ${{ vars.HOST_KEY }}
          port: ${{ vars.HOST_PORT }}
          script: |
            sudo docker rm -f moim
            sudo docker image rm ${{ vars.DOCKER_REPO }} -f
            sudo docker pull ${{ vars.DOCKER_REPO }}
            sudo docker run --name moim --network host -d -v ~/moimPhoto/:/moimPhoto/ -p 8080:8080 ${{ vars.DOCKER_REPO }} --restart on-failure
